[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
homepage = "#website#"
repository = "https://github.com/bahrom04-lab/element-desktop-leveldb"
description = "Letʻs see whatʻs inside leveldb"
authors = ["bahrom04"]

[workspace]
resolver = "3"

members = [
    "crates/element-metadata",
    "crates/element-metadata-cli",
    "crates/element-metadata-gui",
]
default-members = ["crates/element-metadata-gui"]
[profile.release]
lto = true

[workspace.dependencies]
