[package]
name = "element-metadata-gui"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "element-desktop-leveldb"
path = "src/main.rs"

[dependencies]
relm4 = { version = "0.9.1", features = ["macros", "libadwaita", "gnome_47"] }
# tokio = { version = "1.50", features = ["full"] }